---
title: "tempo report"
author: "`r Sys.getenv('USER')`"
date: "`r Sys.Date()`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r functions, echo = FALSE}
source("r-helpers.R")
```


Inputs {.sidebar}
--------------------------------------------------

[Rmarkdown](http://rmarkdown.rstudio.com)


```{r environment, echo = FALSE}
# For this to work, these needs to be set in **$HOME/.Renviron**
TEMPO_KEY <- Sys.getenv("TEMPO_KEY")
check.if.empty(TEMPO_KEY, "TEMPO_KEY")
TEMPO_START <- Sys.getenv("TEMPO_START")
check.if.empty(TEMPO_START, "TEMPO_START")
TEMPO_DAILY <- Sys.getenv("TEMPO_DAILY")
# No checking for this, can be set this way, or through a config/workinghours.csv file
# TEMPO_DAILY is the needed working ours per day, assuming a 5 day work week
TEMPO_TEAM <- Sys.getenv("TEMPO_TEAM")
# No check, does not have to be set
WD_KEY <- Sys.getenv("ARBETSDAGAR_KEY")
check.if.empty(WD_KEY, "WD_KEY")
```

```{r libraries, echo = FALSE, warning = FALSE, message = FALSE}

packages <- c("tidyverse", "jsonlite", "httr", "stringr", "slider", "lubridate")
check.packages(packages)

library(tidyverse)
library(dplyr)
library(httr)
library(jsonlite)
library(stringr)
library(slider)
library(lubridate)
```

```{r fetch-helpers, echo = FALSE, message = FALSE}
TEMPO_URL <- "https://api.tempo.io/core/3/"

fetch.tempo <- function(url, query, key) {
  url <- paste0(url, query)
  header <- paste0("Bearer ", key)
  message(url)
  httpResponse <- GET(
    url,
    add_headers("Authorization" = header),
    accept_json(),
    timeout(20)
  )

  return(fromJSON(content(httpResponse, "text")))
}

fetch.tempo.teams <- function(url, key) {
  query <- "teams"
  data <- fetch.tempo(url, query, key)
  # print(paste("Found", data$metadata, "teams"))
  return(data$result)
}

fetch.tempo.data <- function(key, begins, ends, team = 0) {
  offset <- 0
  count <- 100
  TEMPO_LIMIT <- count

  while (count == TEMPO_LIMIT) {
    TEAM_QUERY <- "worklogs"
    if (team != 0) {
      TEAM_QUERY <- paste0(TEAM_QUERY, "/team/", team)
    }
    TEMPO_QUERY <- paste0(
      TEAM_QUERY,
      "?from=", begins,
      "&to=", ends,
      "&offset=", offset,
      "&limit=", TEMPO_LIMIT
    )
    results <- fetch.tempo(TEMPO_URL, TEMPO_QUERY, key)
    count <- results$metadata$count
    if (offset == 0) {
      data <- results$results
    } else {
      data <- bind_rows(data, results$results)
    }
    offset <- offset + TEMPO_LIMIT
  }
  return(data)
}
```

```{r read-csv-file, echo = FALSE}
read.csv.file <- function(file) {
  stopifnot(file != "")
  result <- c()

  if (file.exists(file)) {
    result <- read.csv(file)
  } else {
    print(paste("No such file:", file))
  }

  return(result)
}
```

```{r aggregate-data, echo = FALSE, warning = FALSE, message = FALSE}

working.hours <- read.csv.file(file = "config/workinghours.csv")

team.data <- fetch.tempo.teams(TEMPO_URL, TEMPO_KEY)
team.data <- subset(team.data, select = c(id, name))
knitr::kable(team.data,
  caption = "Teams",
  col.names = capwords(names(team.data))
)

if (TEMPO_TEAM != "") {
  teams <- c(TEMPO_TEAM)
} else {
  teams <- team.data$id
}

aggregated.data <- tibble()

for (team in teams) {
  tempo.data <- fetch.tempo.data(TEMPO_KEY, TEMPO_START, Sys.Date(), team)

  aggregated.team.data <- tibble()

  if (length(tempo.data) > 0) {
    aggregated.team.data <- tempo.data %>%
      mutate(
        user = author$displayName,
        hours = timeSpentSeconds / (60 * 60),
        billable = billableSeconds / (60 * 60),
        date = as.Date(startDate),
        key = str_replace(issue$key, "-.*", ""),
        issue.key = issue$key,
        team = team
      )
    aggregated.data <- bind_rows(aggregated.data, aggregated.team.data)
  }
}

if (!length(aggregated.data) > 0) {
  stop("Could not fetch any data")
}
```

```{r data-generators, echo = FALSE}
#
source("data-helpers.R")
```

```{r ggplot-helpers, echo = FALSE}
#
source("ggplot-helpers.R")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE, results = "asis"}

teams.with.data <- levels(factor(aggregated.data$team))
```

Select a Team with data from the list

```{r input, echo = FALSE}
library(shiny)
inputPanel(
  selectInput("team.id", label = "Team Id: ", choices = c("", teams.with.data), selected = NA)
)
```

Vis {.tabset}
--------------------------------------------------


<!--Visualizations {data-icon="fa-signal"}
===================================== 
-->

### User Delta

```{r echo = FALSE, context = "server", results = "asis"}

# renderText({
#   if (input$team.id != "") {
#     paste("\nTeam: ", subset(team.data, id == input$team.id)$name)
#   }
# })

renderTable(
  {
    if (input$team.id != "") {
      user.delta <- gen.user.delta(aggregated.data, input$team.id, working.hours, WD_KEY, TEMPO_DAILY)
    }
  },
  striped = TRUE
)
```

### Accumulated

```{r echo = FALSE, context = "server", results = "asis"}
renderPlot({
  if (input$team.id != "") {
    user.delta <- gen.user.delta(aggregated.data, input$team.id, working.hours, WD_KEY)
    accumulated <- accumulated.plot(user.delta)
    plot(accumulated)
  }
})

```

### Team Summary

```{r echo = FALSE, context = "server", results = "asis"}

renderPlot({
  if (input$team.id != "") {
    user.summary <- gen.user.summary(aggregated.data, input$team.id)
    team.summary <- gen.team.summary(user.summary)
    team <- team.plot(team.summary)
    plot(team)
  }
})

```

### User Summary

```{r echo = FALSE, context = "server", results = "asis"}
renderPlot({
  if (input$team.id != "") {
    user.summary <- gen.user.summary(aggregated.data, input$team.id)
    rolling <- rolling.plot(user.summary)
    plot(rolling)
  }
})

```

### Daily Plot

```{r echo = FALSE, context = "server", results = "asis"}
renderPlot({
  if (input$team.id != "") {
    tempo <- tempo.daily.plot(aggregated.data, input$team.id)
    plot(tempo)
  }
})

```

### Last 2 weeks

```{r echo = FALSE, context = "server", results = "asis"}
renderPlot({
  if (input$team.id != "") {
    tempo.detailed <- tempo.detailed.plot(aggregated.data, input$team.id)
    plot(tempo.detailed)
  }
})

```

### Issue key hours

#### Worked hours by tempo key

Added as a way to check if keys reported on have correct \"billable\" configuration in Tempo.

```{r echo = FALSE, context = "server", results = "asis"}

renderTable(
  {
    if (input$team.id != "") {
      key.data <- gen.key.data(aggregated.data, input$team.id)
    }
  },
  striped = TRUE,
  hover = TRUE,
  bordered = TRUE
)
```
