name: generate-report-html

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: verifa/tempo-config
          path: ./config
          token: ${{ secrets.TUNABOAT_GITHUB_API }}
      - name: build
        run: |
          cp -R ./config ./shiny/config
          echo TEMPO_KEY=${{ secrets.TEMPO_API }} >> .Renviron
          echo TEMPO_START=2021-01-01 >> .Renviron
          echo ARBETSDAGAR_KEY=${{ secrets.ARBETSDAGAR_KEY }} >> .Renviron
          make build
      - name: gcp auth
        if: github.ref == 'refs/heads/main'
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_JSON_KEY }}"
      - name: setup gcloud sdk
        if: github.ref == 'refs/heads/main'
        uses: "google-github-actions/setup-gcloud@v0"
      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: docker login
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev -q
      - name: docker push
        if: github.ref == 'refs/heads/main'
        run: |
          make push
