name: generate-report-html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: verifa/tempo-config
        path: ./config
        token: ${{ secrets.TUNABOAT_GITHUB_API }}
    - name: Build the shiny image
      run: |
        echo TEMPO_KEY=${{ secrets.TEMPO_API }} >> $HOME/.Renviron
        echo TEMPO_START=2021-01-01 >> $HOME/.Renviron
        echo ARBETSDAGAR_KEY=${{ secrets.ARBETSDAGAR_KEY }} >> $HOME/.Renviron
        make shiny-server
        docker image ls
### Run actions to publish the image 
#    - uses: browser-actions/setup-chrome@latest
#      if: steps.diffcheck.outputs.OUTPUT == 1
